Kluczowe pojęcia :

*    http://camel.apache.org/maven/camel-2.13.0/camel-core/apidocs/org/apache/camel/Message.html[Messages]

*    http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/ExchangePattern.html[Exchanges]

*    http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/CamelContext.html[Camel contexts]

*    http://camel.apache.org/components.html[Components]

*    http://camel.apache.org/routes.html[routes]

*    http://camel.apache.org/message-channel.html[channels]


Stwórz prosty serwis Camela.

TIP: Main

----
  Main main = new Main();
  main.enableHangupSupport();
  main.addRouteBuilder(new MyRouteBuilder());
  main.run(args);   
----

----
 
CamelContext camelContext = new DefaultCamelContext();
camelContext.addRoutes(....);
camelContext.setTracing(true);
camelContext.start();
Thread.sleep(10000);
camelContext.stop();

----



----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">

    <camelContext xmlns="http://camel.apache.org/schema/spring">
        <route>
            <from uri="file://source"/>
            <to uri="log://org.apache.camel?showAll=true&amp;multiline=true"/>
            <to uri="file://target"/>
        </route>
    </camelContext>

</beans>
----


Przykład 2 

----

<dependency>
<groupId>org.apache.camel</groupId>
<artifactId>camel-core</artifactId>
<version>${camel-version}</version>
</dependency>


public class Main {
public static void main(String[] args) throws Exception
{
CamelContext camelContext = new DefaultCamelContext();
camelContext.addRoutes(new MyFileRoute());
camelContext.start();
Thread.sleep(10000);
camelContext.stop();
}
}
----

Stwórz serwis Camel wraz z integracją z Spring Boot

TIP: RouteBuilder

----
CamelSpringBootApplicationController
----

TIP: katalog routes

----
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns="http://camel.apache.org/schema/spring">
    <route id="test-route">
        <from uri="timer://myTimer?period={{timer.period}}&amp;delay=1000&amp;repeatCount=5" />
        <process ref="...." />
        <bean ref="..." method="...." />
        <to uri="log:timer?level=INFO&amp;showHeaders=true" />
    </route>
</routes>
----

Sparametryzuj Route

----
<route>
<from uri="{{start.endpoint}}"/>
<transform>
<simple>{{transform.message}}: ${body}</simple>
</transform>
<to uri="{{end.endpoint}}"/>
</route>
----

----
PropertiesComponent properties = new PropertiesComponent();
properties.setLocation("classpath:placeholder.properties");
camelContext.addComponent(properties);
----


Stwórz prosty timer i wyrzuć tekst na konsole, do pliku i do logów.

----
<route>
<from uri="timer://start?fixedRate=true&amp;period=1000"/>
<to uri="log://org.apache.camel.generator?level=INFO"/>
<to uri="direct:logger"/>
</route>
----



Stwórz prosty procesor

Stwórz prosty bean i wykorzystaj go w trasie


----
from(...).bean(MyService.class, "doSomething(${body},${header.userId})")
----

----
from(...).to("bean:myService?method=doSomething(${body.asXml},${header.userId})")
----


Zarejestruj bean


----
public class MySimpleBean {
public String hello(String message) {
return "Hello" + message;
}
}

SimpleRegistry registry = new SimpleRegistry();
registry.put("myBean", new MySimpleBean());
CamelContext camelContext = new DefaultCamelContext(registry);

...

from("direct:start").to("bean:simpleBean").to("mock:stop");
----

** ApplicationContextRegistry - automatyczna rejestracja z kontekstu springa

Użyj #Beana Springowego


Użyj #@Handle w celu rozpoznania właściwej metody ServiceActivator 


TIP : wykorzystaj #Direct


TIP: wykorzystaj #SEDA

Użyj #LogComponents

----
<?xml version="1.0" encoding="UTF-8"?>
<person user="james">
  <firstName>James</firstName>
  <lastName>Strachan</lastName>
  <city>London</city>
</person>
----

----
<?xml version="1.0" encoding="UTF-8"?>
<person user="ibsen">
  <firstName>Claus</firstName>
  <lastName>Ibsen</lastName>
  <city>new york</city>
</person>
----

Wyłącz Route

----
context.stopRoute(routeName);
----

TIP: Użyj wątek

Sposób 2:

----
.to("controlbus:route?routeId=mainRoute&action=stop&async=true")
----


Stwórz implementacje CBR

TIP: xpath("/person/city = 'London'")

Ukryć

----

from("file:src/data?noop=true")
            .choice()
                .when(xpath("/person/city = 'London'"))
                    .log("UK message")
                    .to("file:target/messages/uk")
                .otherwise()
                    .log("Other message")
                    .to("file:target/messages/others");
}
----


Przykład 2 : 

----
from("file://source").choice()
.when(simple("${in.header.CamelFileName} contains 'my.txt'")).to("file://my")
.when(simple("${in.header.CamelFileName} contains 'your.txt'")).to("file://your")
.otherwise().to("log://org.apache.camel.howto?showAll=true");
----

Usuń niechciane wiadomości

TIP : #Filter

----
   from("direct:start").filter(header("status").isEqualTo("valid")).to("mock:valid").end()
----


Użyj filter (Bean Binding)

----
filter().method("myFilterBean", "isValid")
----

----
public boolean isValid(@Header("myId") String userId, @Body String body, Exchange exchange)
----

lub 

----
filter().method("myFilterBean", "isValid(@Header("userId"),${body}, null)")
----


Użyj Predicate


----
public class MyPredicate {
public boolean isValid(String body) {
}
}
----


Użyj #PipeLine

W postaci jawnej i nie jawnej


Użyj mechanizm #Point-To-Point

timer
set Body 
jms1 -> delay -> log
jms2 -> delay -> log


Użyj mechanizm #Sub-Pub

timer
set Body
jms1 -> delay -> log
jms2 -> delay -> log






Użyj #resequencer do posortowania wiadomości 

----
  from("direct:start")
                .resequence(header("index"))
                .batch().size(100).timeout(1000L)
                .to("mock:result");
}
----

Przetransformuj xml na json


----
 XmlJsonDataFormat
----

----
<dataFormats>
<xmljson id="xmljsonWithOptions" forceTopLevelObject="true" trimSpaces="true" skipNamespaces="true"
removeNamespacePrefixes="true"/>
</>
----

----
<route>
<from uri="direct:start"/>
 <marshal ref="xmljsonWithOptions"/>
<to uri="direct:result"/>
</route>
----

==Wykonaj transformacje : 


* **EL**

----
</transform>
<simple>New message ${body}</simple>
</transform>
----

* **JAVA**

----
.to("bean:myConverter?method=convert(${body}, ${header.userId})")
----

* **PROCESSOR**

----
from("...")
.process(new Processor() {
 public void process(Exchange exchange) throws Exception {
   exchange.getIn().setBody("Changed body");
 }
})
.to("...");
----

===Json

----
unmarshal(new JacksonDataFormat(User.class))
----



=== XML JAXB

----
final DataFormat jaxb = new JaxbDataFormat(JAXBContext.newInstance(User.class));
----


=== Xml Xstream


=== JSON -> XML

=== XML -> JSON


=== Type conversion

----
from(...).convertBodyTo(String.class).to(...)
----

----
Message in = exchange.getIn();
Document document = in.getBody(Document.class);
----

----
public void testRemoveTypeConverter() {
        DefaultCamelContext context = new DefaultCamelContext();        
        context.getTypeConverterRegistry().addTypeConverter(MyOrder.class, String.class, new MyOrderTypeConverter());

        MyOrder order = context.getTypeConverter().convertTo(MyOrder.class, "123");
        assertNotNull(order);
        assertEquals(123, order.getId());

        // now remove it
        boolean removed = context.getTypeConverterRegistry().removeTypeConverter(MyOrder.class, String.class);
        assertTrue("Type converter should be removed", removed);

        order = context.getTypeConverter().convertTo(MyOrder.class, "123");
        assertNull("Type converter should be removed", order);
}
----

----
private static class MyOrder {
        private int id;

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }
    }


    private static class MyOrderTypeConverter extends TypeConverterSupport {

        @SuppressWarnings("unchecked")
        public <T> T convertTo(Class<T> type, Exchange exchange, Object value) {
            MyOrder order = new MyOrder();
            order.setId(Integer.parseInt(value.toString()));
            return (T) order;
        }
    }

----


=== Data Format

----
from("jms:queue:my").unmarshal("jaxb").to("jms:queue:yours")

from("file:data/inbox").unmarshal().serialization().marshall("jaxb").to("jms:queue:yours")
----


Wykorzystaj #Consumer

----
ConsumerTemplate consumerTemplate = camelContext().createConsumerTemplate();
String result = consumerTemplate.receiveBody("activemq:my.queue",String.class);
----

@Consume

----
public class Mdb {
@Consume(uri="activemq:queue:my")
public String onMyMessage(String message) {
return "Hello " + message;
}
}
----

----
public class MyBean {
@Consume(uri="someEndpoint")
public String myMethod(String message) {
//...
}
}

public class MyBean {
@Consume(uri="someEndpoint")
public String myMethod(String message) {
//...
}
}
----


Wykorzystaj #Producer

----
ProducerTemplate producerTemplate = camelContext.createProducerTemplate();
template.sendBody("direct:my", "<hello>world!</hello>");
----

----
public class MyProducer {
@Produce
private ProducerTemplate template;
public String sayHello(String name) {
return template.requestBody("activemq:queue:my",name, String.class);
}
}

Użyj #multicast

----
from("direct:start")
.multicast()
.parallelProcessing().stopOnException(false)
.to("direct:a", "direct:b", "direct:c")
.end()
.to("direct:result");
----

lub static 

----
<multicast>
<to uri="direct:a"/>
<to uri="direct:b"/>
<to uri="direct:c"/>
</multicast>
----

lub dynamicznie  **Recipient List**




Użyj #idempotentConsumer

Użyj #loadBalancer


----
<loadBalance>
<roundRobin/>
<to uri="direct:a"/>
<to uri="direct:b"/>
<to uri="direct:c"/>
</loadBalance>

----

Użyj #Throttle

----
<route>
<from uri="seda:a"/>
<throttle maximumRequestsPerPeriod="10" timePeriodMillis="10000">
<to uri="direct:next"/>
</throttle>
</route>
----


Użyj #Delayer

----
public class DelayBean {
public int delay() {
Random random = new Random();
return random.nextInt(10000);
}
}
----

Użyj #Loop


Użyj #Splitter


** XPATH

----
<invoice>
<item><product name="tv" quantity="3"/></item>
<item><product name="playStation" quantity="51"/></item>
</invoice>
----


----
from("direct:start")
.split(xpath("//invoice/item/product")).to("direct:products").end().to("direct:result");
----

Użyj #Aggregator

Prosty przykład

----
public class StringAggregator implements AggregationStrategy {
public Exchange aggregate(Exchange oldExchange, Exchange
newExchange) {
if (oldExchange == null) {
return newExchange;
}
String oldBody = oldExchange.getIn().getBody(String.class);
String newBody = newExchange.getIn().getBody(String.class);
oldExchange.getIn().setBody(oldBody + "+" + newBody);
return oldExchange;
}
}
----


Użyj #DynamicRouter

Użyj # WireTap

----
<route>
<from uri="timer:fire?period=5000"/>
<setBody><constant>Hello !!</constant></setBody>
<wireTap uri="direct:wiretap"/>
<delay>
<constant>3000</constant>
<to uri="log:main"/>
</delay>
</route>
----

Użyj asynchroniczność w taskach które się długo procesują 

TIP: SEDA

TIP: concurrentConsumers

Wykorzystaj obsługę błędów

# DeadLetterChannel

# DefaultErrorHandler

# NoErrorHandler

# LoggingErrorHandler

# Redelivery

# Exception policy

# Handling and ignoring exceptions


