

Stwórz prosty serwis Camela.

TIP: Main

----
  Main main = new Main();
  main.enableHangupSupport();
  main.addRouteBuilder(new MyRouteBuilder());
  main.run(args);   
----

----
 
CamelContext camelContext = new DefaultCamelContext();
camelContext.addRoutes(....);
camelContext.setTracing(true);
camelContext.start();
Thread.sleep(10000);
camelContext.stop();

----



----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">

    <camelContext xmlns="http://camel.apache.org/schema/spring">
        <route>
            <from uri="file://source"/>
            <to uri="log://org.apache.camel?showAll=true&amp;multiline=true"/>
            <to uri="file://target"/>
        </route>
    </camelContext>

</beans>
----


Przykład 2 

----

<dependency>
<groupId>org.apache.camel</groupId>
<artifactId>camel-core</artifactId>
<version>${camel-version}</version>
</dependency>


public class Main {
public static void main(String[] args) throws Exception
{
CamelContext camelContext = new DefaultCamelContext();
camelContext.addRoutes(new MyFileRoute());
camelContext.start();
Thread.sleep(10000);
camelContext.stop();
}
}
----

Stwórz serwis Camel wraz z integracją z Spring Boot

TIP: RouteBuilder

----
CamelSpringBootApplicationController
----

TIP: katalog routes

----
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns="http://camel.apache.org/schema/spring">
    <route id="test-route">
        <from uri="timer://myTimer?period={{timer.period}}&amp;delay=1000&amp;repeatCount=5" />
        <process ref="...." />
        <bean ref="..." method="...." />
        <to uri="log:timer?level=INFO&amp;showHeaders=true" />
    </route>
</routes>
----


Stwórz prosty timer i wyrzuć tekst na konsole, do pliku i do logów.

----
<route>
<from uri="timer://start?fixedRate=true&amp;period=1000"/>
<to uri="log://org.apache.camel.generator?level=INFO"/>
<to uri="direct:logger"/>
</route>
----



Stwórz prosty procesor

Stwórz prosty bean i wykorzystaj go w trasie


----
from(...).bean(MyService.class, "doSomething(${body},${header.userId})")
----

----
from(...).to("bean:myService?method=doSomething(${body.asXml},${header.userId})")
----

TIP : wykorzystaj #Direct


TIP: wykorzystaj #SEDA



----
<?xml version="1.0" encoding="UTF-8"?>
<person user="james">
  <firstName>James</firstName>
  <lastName>Strachan</lastName>
  <city>London</city>
</person>
----

----
<?xml version="1.0" encoding="UTF-8"?>
<person user="ibsen">
  <firstName>Claus</firstName>
  <lastName>Ibsen</lastName>
  <city>new york</city>
</person>
----

Stwórz implementacje CBR

TIP: xpath("/person/city = 'London'")

Ukryć

----

from("file:src/data?noop=true")
            .choice()
                .when(xpath("/person/city = 'London'"))
                    .log("UK message")
                    .to("file:target/messages/uk")
                .otherwise()
                    .log("Other message")
                    .to("file:target/messages/others");
}
----


Przykład 2 : 

----
from("file://source").choice()
.when(simple("${in.header.CamelFileName} contains 'my.txt'")).to("file://my")
.when(simple("${in.header.CamelFileName} contains 'your.txt'")).to("file://your")
.otherwise().to("log://org.apache.camel.howto?showAll=true");
----

Usuń niechciane wiadomości

TIP : #Filter

----
   from("direct:start").filter(header("status").isEqualTo("valid")).to("mock:valid").end()
----


Użyj filter (Bean Binding)

----
filter().method("myFilterBean", "isValid")
----

----
public boolean isValid(@Header("myId") String userId, @Body String body, Exchange exchange)
----

lub 

----
filter().method("myFilterBean", "isValid(@Header("userId"),${body}, null)")
----
Użyj resequencer do posortowania wiadomości 

----
  from("direct:start")
                .resequence(header("index"))
                .batch().size(100).timeout(1000L)
                .to("mock:result");
}
----

Przetransformuj xml na json


----
 XmlJsonDataFormat
----

----
<dataFormats>
<xmljson id="xmljsonWithOptions" forceTopLevelObject="true" trimSpaces="true" skipNamespaces="true"
removeNamespacePrefixes="true"/>
</>
----

----
<route>
<from uri="direct:start"/>
 <marshal ref="xmljsonWithOptions"/>
<to uri="direct:result"/>
</route>
----

==Wykonaj transformacje : 


* **EL**

----
</transform>
<simple>New message ${body}</simple>
</transform>
----

* **JAVA**

----
.to("bean:myConverter?method=convert(${body}, ${header.userId})")
----

* **PROCESSOR**

----
from("...")
.process(new Processor() {
 public void process(Exchange exchange) throws Exception {
   exchange.getIn().setBody("Changed body");
 }
})
.to("...");
----

===Json

----
unmarshal(new JacksonDataFormat(User.class))
----

=== XML JAXB

----
final DataFormat jaxb = new JaxbDataFormat(JAXBContext.newInstance(User.class));
----


=== Xml Xstream


=== JSON -> XML

=== XML -> JSON


=== Type conversion

----
from(...).convertBodyTo(String.class).to(...)
----


Wykorzystaj #Consumer

----
ConsumerTemplate consumerTemplate = camelContext().createConsumerTemplate();
String result = consumerTemplate.receiveBody("activemq:my.queue",String.class);
----


Wykorzystaj #Producer

----
ProducerTemplate producerTemplate = camelContext.createProducerTemplate();
template.sendBody("direct:my", "<hello>world!</hello>");
----

Użyj #multicast

----
from("direct:start")
.multicast()
.parallelProcessing().stopOnException(false)
.to("direct:a", "direct:b", "direct:c")
.end()
.to("direct:result");
----


Użyj #idempotentConsumer

Użyj #loadBalancer

Użyj #Throttle

----
<route>
<from uri="seda:a"/>
<throttle maximumRequestsPerPeriod="10" timePeriodMillis="10000">
<to uri="direct:next"/>
</throttle>
</route>
----

Użyj #Splitter


** XPATH

----
<invoice>
<item><product name="tv" quantity="3"/></item>
<item><product name="playStation" quantity="51"/></item>
</invoice>
----


----
from("direct:start")
.split(xpath("//invoice/item/product")).to("direct:products").end().to("direct:result");
----

Użyj #Aggregator

