:numbered:
:icons: font
:pagenums:
:imagesdir: images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

:image-link: https://pbs.twimg.com/profile_images/425289501980639233/tUWf7KiC.jpeg
ifndef::sourcedir[:sourcedir: ./src/main/java/]
ifndef::resourcedir[:resourcedir: ./src/main/resources/]
ifndef::imgsdir[:imgsdir: ./../images]
:source-highlighter: coderay


== Wydajność 


== Pule wątków


.Thread pool
[width="100%",frame="topbot",options="header,footer"]
|======================
|Thread Option| Wartość domyślna
|maxQueueSize|    1000
|poolSize|    10
|maxPoolSize|     20
|keepAliveTime|   60 (seconds)
|rejectedPolicy|  CallerRuns
|======================

=== Zmiana wartości domyślnych


----
// Java
import org.apache.camel.spi.ExecutorServiceManager;
import org.apache.camel.spi.ThreadPoolProfile;
...
ExecutorServiceManager manager = context.getExecutorServiceManager();
ThreadPoolProfile defaultProfile = manager.getDefaultThreadPoolProfile();

defaultProfile.setPoolSize(3);
defaultProfile.setMaxQueueSize(100);
...

----

Spring XML : 

----
<camelContext id="camel" xmlns="http://camel.apache.org/schema/spring">
    <threadPoolProfile
        id="changedProfile"
        defaultProfile="true"
        poolSize="3"
        maxQueueSize="100"/>
    ...
</camelContext>
----

=== Tworzenie własnej puli 

----
// Java
import org.apache.camel.builder.ThreadPoolBuilder;
import java.util.concurrent.ExecutorService;
...
ThreadPoolBuilder poolBuilder = new ThreadPoolBuilder(context);
ExecutorService customPool = poolBuilder.poolSize(5).maxPoolSize(5).maxQueueSize(100).build("customPool");
...

from("direct:start")
  .multicast().executorService(customPool)
    .to("mock:first")
    .to("mock:second")
    .to("mock:third");
----

Spring XML : 

----
<camelContext id="camel" xmlns="http://camel.apache.org/schema/spring">
    <threadPool id="customPool"
                poolSize="5"
                maxPoolSize="5"
                maxQueueSize="100" />

    <route>
        <from uri="direct:start"/>
        <multicast executorServiceRef="customPool">
            <to uri="mock:first"/>
            <to uri="mock:second"/>
            <to uri="mock:third"/>
        </multicast>
    </route>
</camelContext>

----
    
== Interfejsy asynchroniczne

----
public interface AsyncProcessor extends Processor {
  boolean process(Exchange exchange, AsyncCallback callback);
}
----

----
public interface AsyncCallback {
void done(boolean doneSync);
}
----

TODO


== Procesowanie plików 

Domyślnie jedno wątkowe

=== Threads EIP

== Wsparcie dla przetwarzania równoległego

** **Aggregator**

** **Delayer**

** **Multicast**

----
from("direct:start")
  .multicast().parallelProcessing()
    .to("mock:first")
    .to("mock:second")
    .to("mock:third");
----

** **Recipient List**

** **Splitter**

----
.split(body().tokenize("\n")).streaming().parallelProcessing()
.bean(Account.class, "csvToObject").to("direct:accountFinished").end()
----


----
ExecutorService threadPool = Executors.newCachedThreadPool();
//...
.split(body().tokenize("\n")).streaming().executorService(threadPool)
.bean(Account.class, "csvToObject")
.to("direct:accountFinished")
.end()
----

*** Z użyciem **SEDA**

*** **Streaming**

Gwarancja iż cały plik czy inny zasób nie zostanie w całości wczytany do pamięci.

Zamiast tego mechanizm czyta kawałek po kawałku powodując tym samym znacznie mniejsze zużycie pamięci


*** **timeout**

Gdy limit czasowy zostanie przekroczony , wszystkie fragmenty które mają zostać odebrane przez pulę wątków zostaną odrzucone, 
a bieżąco przetwarzane fragementy mają szansę jeszcze się przeprocesować.

----
.split(body()).parallelProcessing().timeout(5000)
----

Przykład : (SEDA w akcji)

----
from("file:assets/accounts")
.log("Starting processing: ${header.CamelFileName}")
.split(body().tokenize("\n")).streaming()
.bean(Account.class, "csvToObject")
.to("seda:update")
.end()
.log("Done processing : ${header.CamelFileName}");

 from("seda:update?concurrentConsumers=20").bean(Account.class, "calculateLoanForCustomer");

----


    
** **Threads**

----
<route>
<from uri="direct:start"/>
<to uri="log:start"/>
<threads threadName="myParallelThreadPool" poolSize="5" maxPoolSize="15" maxQueueSize="250">
<to uri="log:myLog"/>
</threads>
</route>
----

Java:

----
from("direct:start").log("Received ${body}:${threadName}")
.threads()
.delay(200)
.log("Processing ${body}:${threadName}")
.to("mock:out");
----


=== ExecutorService threadPool = Executors.newFixedThreadPool(20);

Aby nie nasycić systemu wątkami


=== ExecutorService threadPool = Executors.newCachedThreadPool();

Automatycznie zwiąkszająca się pula w razie takiej potrzeby



** **Throttler**

** **Wire Tap**     

----
<wireTap uri="direct:tap" executorServiceRef="myParallelThreadPool"/>
----

== SEDA , VM

** **concurrentConsumers** 

----
<from uri="seda:in?concurrentConsumers=10"/>
<delay>
<constant>400</constant> <!--symulacja wolnego elementu -->
</delay>
<log message="Processing ${body}:${threadName}"/>
<to uri="mock:out"/>
----

Java: 

----
from("seda:in?concurrentConsumers=10").delay(200).log("Processing ${body}:${threadName}")
.to("mock:out");

----

== JMS, ActiveMQ 

** **concurrentConsumers** 

definiuje minimalny rozmiar puli 

** **maxConcurrentConsumers**

 == JETTY
 
 ** **minThreads** 
 
 definiuje minimalny rozmiar puli 
 
 
 ** **maxThreads**
 
  definiuje maksymalmy rozmiar puli
 
 
== Request

----
from("direct:processInOut").log("Received ${body}")
.delay(1000) 
.log("Processing ${body}")
.transform(simple("Processed ${body}"));
----

----
Future<Object> future = producerTemplate.asyncRequestBody("direct:processInOut", "SomePayload");
----

----
while(!future.isDone()) {
 log.info("...");
Thread.sleep(200);
}

//sprawdzenie :

String response = (String) future.get();
log.info("Received a response");
assertEquals("Processed SomePayload", response);
----


=== Callback

----
Future<Object> future = template.asyncCallbackRequestBody("direct:processInOut","AnotherPayload", new Synchronization() {
@Override
public void onComplete(Exchange exchange) {
   assertEquals("Processed AnotherPayload",
   exchange.getOut().getBody());
  }
@Override
public void onFailure(Exchange exchange) {
  fail();
}
});
----

